// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THESISMATESystem.Server.Data;

#nullable disable

namespace THESISMATESystem.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.CapstoneGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefenseOutcome")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ManuscriptDueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ManuscriptLocked")
                        .HasColumnType("bit");

                    b.Property<int>("ManuscriptRevision")
                        .HasColumnType("int");

                    b.Property<string>("ManuscriptVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReDefense")
                        .HasColumnType("bit");

                    b.Property<int>("RevisionLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SystemFeaturesDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TitleApproved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId");

                    b.ToTable("CapstoneGroups");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ChapterSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("ChapterSubmissions");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacultyICId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyICId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ClassroomAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TargetGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("PostedById");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("ClassroomAnnouncements");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ClassroomEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassroomId", "StudentId")
                        .IsUnique();

                    b.ToTable("ClassroomEnrollments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterSubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscussionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId");

                    b.HasIndex("CapstoneGroupId");

                    b.HasIndex("ChapterSubmissionId");

                    b.ToTable("ConsultationLogs");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("ConsultationScheduleId", "CapstoneGroupId")
                        .IsUnique();

                    b.ToTable("ConsultationRequests");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyICId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxGroups")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyICId");

                    b.ToTable("ConsultationSchedules");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("DefenseCriteria");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefenseCriterionId")
                        .HasColumnType("int");

                    b.Property<int>("DefenseScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("PanelistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DefenseCriterionId");

                    b.HasIndex("PanelistId");

                    b.HasIndex("DefenseScheduleId", "DefenseCriterionId", "PanelistId")
                        .IsUnique();

                    b.ToTable("DefenseRatings");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsRatingOpen")
                        .HasColumnType("bit");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.ToTable("DefenseSchedules");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DocumentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentSubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DocumentSubmissionId");

                    b.ToTable("DocumentComments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DocumentSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAutoFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginalDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.HasIndex("OriginalDocumentId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("DocumentSubmissions");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.GroupDeadline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupDeadlines");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CapstoneGroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptFinalizationVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CapstoneGroupId", "UserId", "Revision")
                        .IsUnique();

                    b.ToTable("ManuscriptFinalizationVotes");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("YjsState")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("CapstoneGroupId", "SectionKey")
                        .IsUnique();

                    b.ToTable("ManuscriptSections");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSectionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CapstoneGroupId");

                    b.ToTable("ManuscriptSectionComments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.ToTable("ManuscriptSnapshots");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedDefenseId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedSystemFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.PanelAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefenseScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("PanelistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PanelistId");

                    b.HasIndex("DefenseScheduleId", "PanelistId")
                        .IsUnique();

                    b.ToTable("PanelAssignments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.RevisionNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterSubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterSubmissionId");

                    b.HasIndex("CreatedById");

                    b.ToTable("RevisionNotes");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CapstoneGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentTestNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentTestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StudentTestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId");

                    b.ToTable("SystemFeatures");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeatureComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemComment")
                        .HasColumnType("bit");

                    b.Property<int>("SystemFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SystemFeatureId");

                    b.ToTable("SystemFeatureComments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeatureScreenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemFeatureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SystemFeatureId");

                    b.ToTable("SystemFeatureScreenshots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.AuditLog", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.CapstoneGroup", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Adviser")
                        .WithMany("AdvisedGroups")
                        .HasForeignKey("AdviserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adviser");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ChapterSubmission", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany("ChapterSubmissions")
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.Classroom", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "FacultyIC")
                        .WithMany()
                        .HasForeignKey("FacultyICId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyIC");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ClassroomAnnouncement", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.Classroom", "Classroom")
                        .WithMany("Announcements")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Classroom");

                    b.Navigation("PostedBy");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ClassroomEnrollment", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.Classroom", "Classroom")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Student")
                        .WithMany("ClassroomEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationLog", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Adviser")
                        .WithMany("ConsultationLogs")
                        .HasForeignKey("AdviserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany("ConsultationLogs")
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ChapterSubmission", "ChapterSubmission")
                        .WithMany()
                        .HasForeignKey("ChapterSubmissionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Adviser");

                    b.Navigation("CapstoneGroup");

                    b.Navigation("ChapterSubmission");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationRequest", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ConsultationSchedule", "ConsultationSchedule")
                        .WithMany("Requests")
                        .HasForeignKey("ConsultationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "RequestedBy")
                        .WithMany("ConsultationRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("ConsultationSchedule");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationSchedule", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "FacultyIC")
                        .WithMany("ConsultationSchedules")
                        .HasForeignKey("FacultyICId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacultyIC");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseRating", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.DefenseCriterion", "DefenseCriterion")
                        .WithMany("DefenseRatings")
                        .HasForeignKey("DefenseCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.DefenseSchedule", "DefenseSchedule")
                        .WithMany("DefenseRatings")
                        .HasForeignKey("DefenseScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Panelist")
                        .WithMany()
                        .HasForeignKey("PanelistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenseCriterion");

                    b.Navigation("DefenseSchedule");

                    b.Navigation("Panelist");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseSchedule", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DocumentComment", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Author")
                        .WithMany("DocumentComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.DocumentSubmission", "DocumentSubmission")
                        .WithMany("Comments")
                        .HasForeignKey("DocumentSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DocumentSubmission");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DocumentSubmission", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.DocumentSubmission", "OriginalDocument")
                        .WithMany()
                        .HasForeignKey("OriginalDocumentId");

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "SubmittedBy")
                        .WithMany("DocumentSubmissions")
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("OriginalDocument");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.GroupDeadline", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.GroupMember", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany("Members")
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptFinalizationVote", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSection", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSectionComment", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CapstoneGroup");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ManuscriptSnapshot", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.Notification", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.PanelAssignment", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.DefenseSchedule", "DefenseSchedule")
                        .WithMany("PanelAssignments")
                        .HasForeignKey("DefenseScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Panelist")
                        .WithMany("PanelAssignments")
                        .HasForeignKey("PanelistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenseSchedule");

                    b.Navigation("Panelist");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.RevisionNote", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ChapterSubmission", "ChapterSubmission")
                        .WithMany("RevisionNotes")
                        .HasForeignKey("ChapterSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChapterSubmission");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeature", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.CapstoneGroup", "CapstoneGroup")
                        .WithMany()
                        .HasForeignKey("CapstoneGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneGroup");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeatureComment", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.ApplicationUser", "Author")
                        .WithMany("SystemFeatureComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("THESISMATESystem.Server.Models.SystemFeature", "SystemFeature")
                        .WithMany("Comments")
                        .HasForeignKey("SystemFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("SystemFeature");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeatureScreenshot", b =>
                {
                    b.HasOne("THESISMATESystem.Server.Models.SystemFeature", "SystemFeature")
                        .WithMany("Screenshots")
                        .HasForeignKey("SystemFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemFeature");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ApplicationUser", b =>
                {
                    b.Navigation("AdvisedGroups");

                    b.Navigation("AuditLogs");

                    b.Navigation("ClassroomEnrollments");

                    b.Navigation("ConsultationLogs");

                    b.Navigation("ConsultationRequests");

                    b.Navigation("ConsultationSchedules");

                    b.Navigation("DocumentComments");

                    b.Navigation("DocumentSubmissions");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("PanelAssignments");

                    b.Navigation("SystemFeatureComments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.CapstoneGroup", b =>
                {
                    b.Navigation("ChapterSubmissions");

                    b.Navigation("ConsultationLogs");

                    b.Navigation("DefenseSchedules");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ChapterSubmission", b =>
                {
                    b.Navigation("RevisionNotes");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.Classroom", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.ConsultationSchedule", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseCriterion", b =>
                {
                    b.Navigation("DefenseRatings");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DefenseSchedule", b =>
                {
                    b.Navigation("DefenseRatings");

                    b.Navigation("PanelAssignments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.DocumentSubmission", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("THESISMATESystem.Server.Models.SystemFeature", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
